apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name}}-service
spec:
  selector:
    app: {{ .Values.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
